run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goimports:
    local-prefixes: github.com/pvxdv/self_improver  # Укажите ваш модуль
  govet:
    shadow: true

linters:
  enable:
    - goimports    # Сортировка импортов
    - govet        # Проверка корректности кода
    - staticcheck  # Статический анализ
    - gosimple     # Упрощение кода
    - errcheck     # Проверка ошибок
    - revive       # Альтернатива golint
  disable:
    - wsl          # Можно отключить, если не нравится стиль пустых строк

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0