services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-local} # prod/dev/local (default_value:local)
    ports:
      - "8080:8080"
    environment:
      #app config
      - APP_ENV=${BUILD_ENV:-local} # prod/dev/local (default_value:local)
      - APP_DEBUG=true
      #http config
      - HTTP_PORT=8080
      - TIMEOUT=5s
      - IDLE_TIMEOUT=60s
      #postgres config
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=self_improver
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: self_improver
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    external: false