-- +goose Up

-- trend
CREATE TABLE IF NOT EXISTS trend (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE
);

-- challenge
CREATE TABLE IF NOT EXISTS challenge (
id SERIAL PRIMARY KEY,
trend_id INTEGER NOT NULL REFERENCES trend(id) ON DELETE CASCADE,
description VARCHAR(1000) NOT NULL,
start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
end_date TIMESTAMP
);

-- debt
CREATE TABLE IF NOT EXISTS debt (
id SERIAL PRIMARY KEY,
description VARCHAR(1000),
amount INTEGER NOT NULL,
return_date TIMESTAMP,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS debt;
DROP TABLE IF EXISTS challenge;
DROP TABLE IF EXISTS trend;
